### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by abecciu** [johnbintz/jasmine-headless-webkit#84]
Hi, just updated my JHW to lastest master to try the sprockets integration. But now I get the error `RangeError: Maximum call stack size exceeded.`.

Here's my jasmine.yml:

``` yaml
src_files:
  - "**/*"

helpers:
  - helpers/**/*

spec_files:
  - "**/*_spec.*"

src_dir:
  - app/javascripts
  - vendor/javascripts

spec_dir: spec

src_paths:
  - "**/*.*"

spec_paths:
  - "**/*[Ss]pec.*"
```

Here's the command I run:

``` bash
$ bundle exec jasmine-headless-webkit -j spec/support/jasmine.yml --color hello_spec.coffee
RangeError: Maximum call stack size exceeded.
```

My ruby version is: `ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin10.8.0]`

The old version `0.7.3.2` worked like a charm. I ran into this problem after the upgrade to master.

Please, let me know if I can help with anything else. Thanks!

**Comment by johnbintz** [comment]
Well first off, you found an error in the docs. :O When I typed `src_paths` I meant `src_files`, so your `jasmine.yml` file should only be:

``` yaml
src_files:
  - "**/*"

helpers:
  - helpers/**/*

spec_files:
  - "**/*[Ss]pec.*"

src_dir:
  - app/javascripts
  - vendor/javascripts

spec_dir: spec
```

Also, did you get a backtrace with that `RangeError`? What is the structure of the files in your source, spec, and helpers directories? Can you gist a couple of the files up so I can take a closer look?
